debug: false
logging:
  level:
    com.fastcampus.projectboard: debug  # root 페이지에서 debug로 선언함
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  profiles:
    active: local # default profile
    group:
      local:
        - common
      prod:
        - common
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project-board
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  h2:
    console:
      enabled: false

---
spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb