debug: false
logging:
  level:
    com.fastcampus.projectboard: debug  # root 페이지에서 debug로 선언함
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  profiles:
    active: heroku # default profile
    group:
      local:
        - common
      prod:
        - common
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/project-board
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    database: mysql
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql.init.mode: always
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
  thymeleaf3.decoupled-logic: true

---
spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: ${CLEARDB_WHITE_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always